In [1]:
import pandas as pd

In [2]:
ces = pd.read_csv('CCES24_Common_OUTPUT_vv_topost_final.csv')
ces.head()

,caseid,tookpost,commonweight,commonpostweight,vvweight,vvweight_post,CCEStake,add_confirm,inputzip,birthyr,...,starttime_post,endtime_post,TS_g2024,TS_voterstatus,TS_p2024,TS_p2024_party,TS_pp2024,TS_pp2024_party,TS_state,TS_partyreg
0,1853651564,2,0.418897,0.180057,1.407497,0.822485,1,1.0,NaN,1978,...,2024-11-09 03:00:05,2024-11-09 03:09:39,3.0,1.0,7.0,NaN,7.0,NaN,PA,2.0
1,1853655732,2,0.946650,0.700897,0.470183,0.435126,1,NaN,11236.0,1968,...,2024-11-10 22:46:35,2024-11-10 22:56:59,2.0,1.0,7.0,NaN,7.0,NaN,NY,8.0
2,1852716424,2,0.194303,0.046275,0.245400,0.172787,1,1.0,NaN,1946,...,2024-11-11 03:52:52,2024-11-11 04:11:38,3.0,1.0,7.0,NaN,7.0,NaN,PA,NaN
3,1853644254,2,0.083223,0.008897,0.465415,0.636743,1,NaN,90039.0,2001,...,2024-12-08 03:31:26,2024-12-08 04:30:16,1.0,1.0,7.0,NaN,7.0,NaN,CA,NaN
4,1853644132,2,0.596598,0.555395,1.676258,1.609462,1,1.0,NaN,1955,...,2024-11-06 23:47:48,2024-11-07 00:27:52,1.0,1.0,1.0,NaN,7.0,NaN,MT,NaN

In [3]:
# find and rename demographic variables
demographic_columns = {
    "educ" : "Education",
    "race" : "Race",
    "hispanic" : "Hispanic",
    "gender4": "Gender",
    "birthyear" : "Birth Year" 
}

In [4]:
# voter outreach columns
voter_outreach_columns = {
    "CC24_431a": "Outreach Y/N",
    "CC24_431b_1": "In person",
    "CC24_431b_2" : "Phone call",
    "CC24_431b_3" : "Email or text message",
    "CC24_431b_4": "Letter or postcard"
}

In [5]:
state_column = {
    "inputstate" : "State"
}

In [9]:
ces.groupby(by='inputstate').count()

,caseid,tookpost,commonweight,commonpostweight,vvweight,vvweight_post,CCEStake,add_confirm,inputzip,birthyr,...,starttime_post,endtime_post,TS_g2024,TS_voterstatus,TS_p2024,TS_p2024_party,TS_pp2024,TS_pp2024_party,TS_state,TS_partyreg
inputstate,,,,,,,,,,,,,,,,,,,,,
1,901,901,901,715,569,507,901,612,346,901,...,715,715,569,569,569,218,569,0,569,2
2,128,128,128,108,96,88,128,96,39,128,...,108,108,96,96,96,0,96,0,96,49
4,1495,1495,1495,1238,1019,925,1495,1096,536,1495,...,1238,1238,1019,1019,1019,642,1016,244,1019,836
5,532,532,532,429,294,272,532,377,186,532,...,429,429,294,294,294,131,293,0,294,2
6,4900,4900,4900,3873,3181,2756,4900,3424,1791,4900,...,3873,3873,3181,3181,3181,0,3176,0,3181,2622
8,1055,1055,1055,850,745,654,1055,803,338,1055,...,850,850,745,745,745,252,743,181,745,416
9,594,594,594,491,372,338,594,398,269,594,...,491,491,372,372,372,0,372,0,372,242
10,219,219,219,176,142,128,219,151,83,219,...,176,176,142,142,142,53,140,0,142,113
11,170,170,170,128,111,87,170,119,74,170,...,128,128,111,111,111,0,109,0,111,92
12,4402,4402,4402,3610,2952,2661,4402,3173,1594,4402,...,3610,3610,2952,2952,2952,1,2947,0,2952,2397
13,2055,2055,2055,1608,1291,1128,2055,1373,839,2055,...,1608,1608,1291,1291,1291,525,1291,424,1291,7
15,183,183,183,165,114,107,183,137,54,183,...,165,165,114,114,114,0,114,0,114,1
16,313,313,313,270,207,193,313,250,87,313,...,270,270,207,207,207,93,207,0,207,156
17,2320,2320,2320,1897,1540,1387,2320,1608,844,2320,...,1897,1897,1540,1540,1540,753,1536,0,1540,2
18,1267,1267,1267,1079,872,819,1267,922,444,1267,...,1079,1079,872,872,872,0,871,0,872,0
19,615,615,615,545,469,440,615,491,171,615,...,545,545,469,469,469,93,468,1,469,361
20,502,502,502,413,364,330,502,378,163,502,...,413,413,364,364,364,0,364,1,364,293
21,887,887,887,746,545,511,887,623,326,887,...,746,746,545,545,545,1,542,0,545,543
22,709,709,709,546,421,379,709,490,244,709,...,546,546,421,421,421,0,419,0,421,352
23,287,287,287,263,203,196,287,218,115,287,...,263,263,203,203,203,0,203,0,203,153
24,1068,1068,1068,853,699,625,1068,738,399,1068,...,853,853,699,699,699,386,699,1,699,576
25,1119,1119,1119,967,783,722,1119,766,483,1119,...,967,967,783,783,783,340,782,425,783,334
26,1951,1951,1951,1649,1374,1273,1951,1389,692,1951,...,1649,1649,1374,1374,1374,0,1369,0,1374,2
27,1016,1016,1016,892,754,701,1016,792,281,1016,...,892,892,754,754,754,0,753,0,754,2
28,503,503,503,384,286,243,503,322,224,503,...,384,384,286,286,286,0,286,0,286,0
29,1323,1323,1323,1135,960,897,1323,990,437,1323,...,1135,1135,960,960,960,1,960,33,960,110
30,231,231,231,202,173,167,231,180,67,231,...,202,202,173,173,173,0,173,0,173,0
31,353,353,353,301,241,229,353,244,137,353,...,301,301,241,241,241,0,241,0,241,192
32,739,739,739,609,459,404,739,505,285,739,...,609,609,459,459,459,0,458,1,443,368
33,298,298,298,268,204,192,298,224,111,298,...,268,268,204,204,204,109,203,136,204,133
34,1604,1604,1604,1336,1104,987,1604,1118,682,1604,...,1336,1336,1104,1104,1104,0,1103,0,1104,851
35,422,422,422,335,277,242,422,303,149,422,...,335,335,277,277,277,113,276,0,277,215
36,3453,3453,3453,2785,2195,1961,3453,2228,1391,3453,...,2785,2785,2195,2195,2195,1,2192,0,2195,1778
37,1913,1913,1913,1558,1253,1133,1913,1366,694,1913,...,1558,1558,1253,1253,1253,657,1250,0,1253,801
38,114,114,114,102,76,74,114,85,35,114,...,102,102,76,76,76,0,76,0,76,1
39,2564,2564,2564,2139,1622,1488,2564,1757,959,2564,...,2139,2139,1622,1622,1622,789,1619,0,1622,4
40,701,701,701,578,433,403,701,506,242,701,...,578,578,433,433,433,1,432,0,433,430
41,1009,1009,1009,880,782,732,1009,813,286,1009,...,880,880,782,782,782,1,781,0,782,632
42,3040,3040,3040,2613,2120,1967,3040,2205,1029,3040,...,2613,2613,2120,2120,2120,1123,2117,1,2120,1885
44,212,212,212,188,145,138,212,139,96,212,...,188,188,145,145,145,42,144,32,145,86
45,992,992,992,810,666,594,992,713,356,992,...,810,810,666,666,666,191,665,315,666,0
46,173,173,173,146,118,112,173,129,56,173,...,146,146,118,118,118,0,118,0,118,107
47,1371,1371,1371,1180,939,868,1371,1035,449,1371,...,1180,1180,939,939,939,356,937,344,939,1
48,4816,4816,4816,3679,2969,2562,4816,3259,1881,4816,...,3679,3679,2969,2969,2969,1396,2964,0,2969,8
49,507,507,507,423,162,152,507,373,174,507,...,423,423,162,162,162,0,162,0,162,129
50,124,124,124,115,90,88,124,95,58,124,...,115,115,90,90,90,0,90,51,90,0
51,1611,1611,1611,1341,1159,1034,1611,1212,523,1611,...,1341,1341,1159,1159,1159,358,1157,496,1159,4
53,1382,1382,1382,1204,1034,956,1382,1049,442,1382,...,1204,1204,1034,1034,1034,0,1031,0,1034,4
54,428,428,428,363,295,277,428,307,148,428,...,363,363,295,295,295,0,295,0,295,227
55,1334,1334,1334,1168,864,816,1334,944,480,1334,...,1168,1168,864,864,864,2,863,0,864,0
56,95,95,95,79,57,54,95,70,32,95,...,79,79,57,57,57,0,56,0,57,51

In [13]:
fips = pd.read_csv('State,_County_and_City_FIPS_Reference_Table_20260719.csv')
fips.head()

,State Name,County Name,City Name,State Code,State FIPS Code,County Code,StCnty FIPS Code,City Code,StCntyCity FIPS Code
0,ALABAMA,AUTAUGA,AUTAUGAVILLE,AL,1,C001,1001.0,220.0,10010220.0
1,ALABAMA,AUTAUGA,BILLINGSLEY,AL,1,C001,1001.0,340.0,10010340.0
2,ALABAMA,AUTAUGA,BOOTH,AL,1,C001,1001.0,425.0,10010425.0
3,ALABAMA,AUTAUGA,JONES,AL,1,C001,1001.0,1796.0,10011796.0
4,ALABAMA,AUTAUGA,MARBURY,AL,1,C001,1001.0,2002.0,10012002.0

In [15]:
fips_state_code = fips.groupby(by=['State Name', 'State Code']).agg({'State FIPS Code': 'max'}).reset_index()
fips_state_code

              State Name State Code  State FIPS Code
0                ALABAMA         AL                1
1                 ALASKA         AK                2
2                ARIZONA         AZ                4
3               ARKANSAS         AR                5
4             CALIFORNIA         CA                6
5               COLORADO         CO                8
6            CONNECTICUT         CT                9
7               DELAWARE         DE               10
8   DISTRICT OF COLUMBIA         DC               11
9                FLORIDA         FL               12
10               GEORGIA         GA               13
11                HAWAII         HI               15
12                 IDAHO         ID               16
13              ILLINOIS         IL               17
14               INDIANA         IN               18
15                  IOWA         IA               19
16                KANSAS         KS               20
17              KENTUCKY         KY               21
18             LOUISIANA         LA               22
19                 MAINE         ME               23
20              MARYLAND         MD               24
21         MASSACHUSETTS         MA               25
22              MICHIGAN         MI               26
23             MINNESOTA         MN               27
24           MISSISSIPPI         MS               28
25              MISSOURI         MO               29
26               MONTANA         MT               30
27              NEBRASKA         NE               31
28                NEVADA         NV               32
29         NEW HAMPSHIRE         NH               33
30            NEW JERSEY         NJ               34
31            NEW MEXICO         NM               35
32              NEW YORK         NY               36
33        NORTH CAROLINA         NC               37
34          NORTH DAKOTA         ND               38
35                  OHIO         OH               39
36              OKLAHOMA         OK               40
37                OREGON         OR               41
38          PENNSYLVANIA         PA               42
39           PUERTO RICO         PR               72
40          RHODE ISLAND         RI               44
41        SOUTH CAROLINA         SC               45
42          SOUTH DAKOTA         SD               46
43             TENNESSEE         TN               47
44                 TEXAS         TX               48
45                  UTAH         UT               49
46               VERMONT         VT               50
47              VIRGINIA         VA               51
48            WASHINGTON         WA               53
49         WEST VIRGINIA         WV               54
50             WISCONSIN         WI               55
51               WYOMING         WY               56

In [16]:
fips_state_code['State Name'] = fips_state_code['State Name'].str.title()

In [17]:
fips_state_code

              State Name State Code  State FIPS Code
0                Alabama         AL                1
1                 Alaska         AK                2
2                Arizona         AZ                4
3               Arkansas         AR                5
4             California         CA                6
5               Colorado         CO                8
6            Connecticut         CT                9
7               Delaware         DE               10
8   District Of Columbia         DC               11
9                Florida         FL               12
10               Georgia         GA               13
11                Hawaii         HI               15
12                 Idaho         ID               16
13              Illinois         IL               17
14               Indiana         IN               18
15                  Iowa         IA               19
16                Kansas         KS               20
17              Kentucky         KY               21
18             Louisiana         LA               22
19                 Maine         ME               23
20              Maryland         MD               24
21         Massachusetts         MA               25
22              Michigan         MI               26
23             Minnesota         MN               27
24           Mississippi         MS               28
25              Missouri         MO               29
26               Montana         MT               30
27              Nebraska         NE               31
28                Nevada         NV               32
29         New Hampshire         NH               33
30            New Jersey         NJ               34
31            New Mexico         NM               35
32              New York         NY               36
33        North Carolina         NC               37
34          North Dakota         ND               38
35                  Ohio         OH               39
36              Oklahoma         OK               40
37                Oregon         OR               41
38          Pennsylvania         PA               42
39           Puerto Rico         PR               72
40          Rhode Island         RI               44
41        South Carolina         SC               45
42          South Dakota         SD               46
43             Tennessee         TN               47
44                 Texas         TX               48
45                  Utah         UT               49
46               Vermont         VT               50
47              Virginia         VA               51
48            Washington         WA               53
49         West Virginia         WV               54
50             Wisconsin         WI               55
51               Wyoming         WY               56

In [20]:
ncsl_classification = pd.read_csv('Voter ID Law Classification.csv')
ncsl_classification.head()

         State NCSL Classification
0     Arkansas     Strict Photo ID
1      Georgia     Strict Photo ID
2      Indiana     Strict Photo ID
3       Kansas     Strict Photo ID
4  Mississippi     Strict Photo ID

In [33]:
# test join
state = pd.DataFrame(ces['inputstate'])
state_to_fips = state.merge(right=fips_state_code, how='left', left_on='inputstate', right_on='State FIPS Code')
fips_to_ncsl = state_to_fips.merge(right=ncsl_classification, how='left', left_on ='State Name', right_on='State')
fips_to_ncsl = fips_to_ncsl.drop(columns='State FIPS Code')

In [34]:
fips_to_ncsl.head()

,inputstate,State Name,State Code,State,NCSL Classification
0,42,Pennsylvania,PA,Pennsylvania,No Document Required to Vote
1,36,New York,NY,New York,No Document Required to Vote
2,42,Pennsylvania,PA,Pennsylvania,No Document Required to Vote
3,6,California,CA,California,No Document Required to Vote
4,30,Montana,MT,Montana,Non Strict Photo ID